'ALTER TABLE provider ADD hash VARCHAR(255) NOT NULL, ADD date_activated DATETIME DEFAULT NULL, CHANGE deleted_by deleted_by INT DEFAULT NULL';
'ALTER TABLE provider ADD CONSTRAINT FK_92C4739C1F6FA0AF FOREIGN KEY (deleted_by) REFERENCES user (id)';
