name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - beta
    pull_request:
        branches:
            - main
            - beta

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install dependencies
              uses: php-actions/composer@v6
              with:
                  args: install --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Remove node_modules
              run: |
                  rm -rf node_modules

            - name: Deploy to test environment
              if: github.ref == 'refs/heads/beta' && github.event_name == 'push'
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  server: ${{ secrets.TEST_FTP_SERVER }}
                  username: ${{ secrets.TEST_FTP_USERNAME }}
                  password: ${{ secrets.TEST_FTP_PASSWORD }}
                  port: 21
                  protocol: ftps
                  local-dir: ./ # Directory to upload
                  server-dir: /www/spravmisluzbu/ # Directory on server

            - name: Deploy to production
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  server: ${{ secrets.PROD_FTP_SERVER }}
                  username: ${{ secrets.PROD_FTP_USERNAME }}
                  password: ${{ secrets.PROD_FTP_PASSWORD }}
                  port: 21
                  protocol: ftps
                  local-dir: ./ # Directory to upload
                  server-dir: /www/ # Directory on server

            - name: Apply database migrations on server (Test environment)
              if: github.ref == 'refs/heads/beta' && github.event_name == 'push'
              run: |
                  curl -fsSL "http://${{ secrets.TEST_FTP_SERVER }}/spravmisluzbu/migrate.php"

            - name: Apply database migrations on server (Production environment)
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: |
                  curl -fsSL "http://${{ secrets.PROD_FTP_SERVER }}/migrate.php"
