name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - beta
    pull_request:
        branches:
            - main
            - beta

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install dependencies
              run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Deploy to test environment
              if: github.ref == 'refs/heads/beta' && github.event_name == 'push'
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  ftp-server: ${{ secrets.TEST_FTP_SERVER }}
                  ftp-username: ${{ secrets.TEST_FTP_USERNAME }}
                  ftp-password: ${{ secrets.TEST_FTP_PASSWORD }}
                  local-dir: ./ # Directory to upload
                  server-dir: /www/spravmisluzbu # Directory on server

            - name: Deploy to production
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  ftp-server: ${{ secrets.PROD_FTP_SERVER }}
                  ftp-username: ${{ secrets.PROD_FTP_USERNAME }}
                  ftp-password: ${{ secrets.PROD_FTP_PASSWORD }}
                  local-dir: ./ # Directory to upload
                  server-dir: /www # Directory on server
