name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - beta
            - dev
    pull_request:
        branches:
            - main
            - beta
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: mbstring, gd

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  composer-options: '--prefer-dist --optimize-autoloader'

            - name: Remove node_modules
              run: |
                  rm -rf node_modules

            - name: Deploy to dev environment
              if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  server: ${{ secrets.DEV_FTP_SERVER }}
                  username: ${{ secrets.DEV_FTP_USERNAME }}
                  password: ${{ secrets.DEV_FTP_PASSWORD }}
                  port: 21
                  protocol: ftp
                  local-dir: ./ # Directory to upload
                  server-dir: /www/subdom/test/ # Directory on server


            - name: Deploy to test environment
              if: github.ref == 'refs/heads/beta' && github.event_name == 'push'
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  server: ${{ secrets.TEST_FTP_SERVER }}
                  username: ${{ secrets.TEST_FTP_USERNAME }}
                  password: ${{ secrets.TEST_FTP_PASSWORD }}
                  port: 21
                  protocol: ftp
                  local-dir: ./ # Directory to upload
                  server-dir: / # Directory on server

            - name: Deploy to production
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  server: ${{ secrets.PROD_FTP_SERVER }}
                  username: ${{ secrets.PROD_FTP_USERNAME }}
                  password: ${{ secrets.PROD_FTP_PASSWORD }}
                  port: 21
                  protocol: ftp
                  local-dir: ./ # Directory to upload
                  server-dir: /www/ # Directory on server

#            - name: Apply database migrations on server (Test environment)
#              if: github.ref == 'refs/heads/beta' && github.event_name == 'push'
#              env:
#                  SSH_PRIVATE_KEY: ${{ secrets.TEST_FTP_PASSWORD }}
#              run: |
#                  echo "${SSH_PRIVATE_KEY}" > ssh_key
#                  chmod 600 ssh_key
#                  ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.TEST_FTP_USERNAME }}@${{ secrets.TEST_FTP_SERVER }} 'cd /www/spravmisluzbu && php bin/console.php migrations:migrate'
#
#            - name: Apply database migrations on server (Production environment)
#              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#              env:
#                  SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
#              run: |
#                  echo "${SSH_PRIVATE_KEY}" > ssh_key
#                  chmod 600 ssh_key
#                  ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.PROD_SSH_USERNAME }}@${{ secrets.PROD_SSH_SERVER }} 'cd /www && php bin/console.php migrations:migrate'
